version: 2.1


jobs:
  print-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello"
  
  print-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Say world"
          command: "echo World"

  print-myname:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: "Say my name"
          command: "echo My name is $MY_NAME"

workflows:
  say-hello-workflow:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
      - print-myname:
          requires:
            - print-world
      
